### ISSUE TITLE
Issue with rake cs:get:list[resource]

### ISSUE THREAD

**Issue by remillet** [collectionspace/csible#17]
'rake cs:get:list[media]' fails with this error:

rake aborted!
Errno::ENOENT: No such file or directory @ rb_file_s_truncate - response.csv
/home/remillet/dev/src/csible/lib/cli/cs.rb:260:in `truncate'
/home/remillet/dev/src/csible/lib/cli/cs.rb:260:in`block (3 levels) in <top (required)>'
/home/remillet/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/remillet/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in`eval'
/home/remillet/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => cs:get:list

Fails on Ubuntu, OS X, and Windows 7

**Comment by mark-cooper** [comment]
Updated to create file if not exists. Was sure former method was doing that once upon a time, but isn't with Ruby 2.3.
