### ISSUE TITLE
Remove dependency on ansible

### ISSUE THREAD

**Issue by remillet** [collectionspace/csible#4]
Would it be possible to remove the dependency on ansible from this project?

**Comment by mark-cooper** [comment]
It certainly would ... I'll just need to get you the drop-off instructions for a briefcase full of ... :smile: 

I think it's the obvious next step for "sibyl". Actually, the first thing to do will be to replace Ansible as the api client with a Ruby gem that can provide at least an equivalent level of functionality (that could go on rubygems.org and be used in other contexts should anyone care to do so). Then replace the calls to Ansible with the Ruby api client.

Further down the line might be replacing the use of Rake for a more natural command line interface library, such as thor. It might even then be wrappable in one of those "create a system executable" type things (fpm, omnibus etc.). But that's all for the future ...

**Comment by mark-cooper** [comment]
Done with:

https://github.com/lyrasis/csible/pull/5
